// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wtdngktnyedimeeugajg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0ZG5na3RueWVkaW1lZXVnYWpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyODAwMjksImV4cCI6MjA2Njg1NjAyOX0.hTMng9dOfeMebqLIJuuBqjQ3NKvY2WC2ZCRcAN45bJg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});